# Generated by Django 5.0.3 on 2024-05-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_remove_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_images/'),
        ),
    ]
