# Generated by Django 5.0.3 on 2024-05-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/'),
        ),
    ]
